# Generated by Django 3.2.6 on 2021-09-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_img', models.ImageField(upload_to='tstudentapp/img')),
                ('student_age', models.IntegerField(null=True)),
                ('student_10', models.IntegerField(null=True)),
                ('student_12', models.IntegerField(null=True)),
                ('student_diploma', models.IntegerField(null=True)),
            ],
        ),
    ]
