# Generated by Django 3.2.6 on 2021-09-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tstudentapp', '0002_auto_20210908_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_branch',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
