# Generated by Django 3.2.6 on 2021-09-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tstudentapp', '0004_auto_20210908_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_10',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
