# Generated by Django 3.2.6 on 2021-09-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tstudentapp', '0005_alter_student_student_10'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_10',
            new_name='student_tenth',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_12',
            new_name='student_twelth',
        ),
    ]
