# Generated by Django 3.2.6 on 2021-09-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tstudentapp', '0009_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
