# Generated by Django 3.2.6 on 2021-10-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tstudentapp', '0011_auto_20211022_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
